CREATE TABLE loginTBL
(
	ID varchar(50)  NOT NULL,
	ROOMID varchar(8)  NOT NULL,
	Name varchar(50),
	LoginTime varchar(24)
);
ALTER TABLE loginTBL ADD CONSTRAINT pk_loginTBL PRIMARY KEY (ID);
CREATE TABLE APIKEYTBL
(
	APPID varchar(100)  NOT NULL,
	APIKEY varchar(100) NOT NULL,
	SECRETKEY varchar(200) NOT NULL,
	USEDTIME timestamp  NOT NULL
);
ALTER TABLE APIKEYTBL ADD CONSTRAINT pk_APIKEYTBL PRIMARY KEY (APPID,APIKEY,SECRETKEY);
CREATE TABLE ROOMTBL
(
	ROOMID varchar(8)  NOT NULL,
	ROOMNAME varchar(100) NOT NULL,
	USEFLAG varchar(1) NOT NULL,
);
ALTER TABLE ROOMTBL ADD CONSTRAINT pk_ROOMTBL PRIMARY KEY (ROOMID);
CREATE TABLE USEROOMTBL
(
	ROOMID varchar(8)  NOT NULL,
	USERID varchar(50) NOT NULL,
	STARTTIME timestamp NOT NULL,
	ENDTIME timestamp NOT NULL,
);
ALTER TABLE USEROOMTBL ADD CONSTRAINT pk_USEROOMTBL PRIMARY KEY (ROOMID,STARTTIME);